/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconIcBaselineFavorite: typeof import('~icons/ic/baseline-favorite.jsx')['default']
  const IconIcOutlineFavoriteBorder: typeof import('~icons/ic/outline-favorite-border.jsx')['default']
}
